const sampleListings = [
  {
    title: "Luxury Beach Villa",
    description: "A beautiful beachfront villa with a private pool and stunning ocean views.",
    location: "Goa",
    country: "India",
    price: 8500,
  },
  {
    title: "Mountain Cabin",
    description: "Cozy wooden cabin surrounded by mountains, perfect for a peaceful getaway.",
    location: "Manali",
    country: "India",
    price: 4200,
  },
  {
    title: "Modern City Apartment",
    description: "Stylish apartment in the heart of the city with all modern amenities.",
    location: "Mumbai",
    country: "India",
    price: 6500,
  },
  {
    title: "Desert Camp",
    description: "Experience the beauty of the desert with traditional food and camel rides.",
    location: "Jaisalmer",
    country: "India",
    price: 3000,
  },
  {
    title: "Lake View Cottage",
    description: "Relax in a peaceful cottage overlooking a beautiful lake.",
    location: "Nainital",
    country: "India",
    price: 4800,
  },
  {
    title: "Snow Resort",
    description: "Enjoy skiing and snowboarding at this premium mountain resort.",
    location: "Gulmarg",
    country: "India",
    price: 9200,
  },
  {
    title: "Heritage Haveli",
    description: "Stay in a royal haveli with authentic Rajasthani architecture.",
    location: "Jaipur",
    country: "India",
    price: 5800,
  },
  {
    title: "Tea Garden Homestay",
    description: "Wake up to breathtaking tea plantations and fresh mountain air.",
    location: "Munnar",
    country: "India",
    price: 3600,
  },
  {
    title: "Forest Treehouse",
    description: "Unique treehouse experience surrounded by lush green forests.",
    location: "Wayanad",
    country: "India",
    price: 5300,
  },
  {
    title: "Luxury Penthouse",
    description: "Spacious penthouse with skyline views and premium facilities.",
    location: "Bengaluru",
    country: "India",
    price: 11000,
  },
  {
    title: "Beach Shack",
    description: "Affordable beach shack just a few steps from the sea.",
    location: "Puri",
    country: "India",
    price: 2200,
  },
  {
    title: "Jungle Safari Lodge",
    description: "Comfortable lodge with exciting wildlife safari experiences.",
    location: "Jim Corbett",
    country: "India",
    price: 4900,
  },
  {
    title: "Hilltop Villa",
    description: "Luxury villa offering panoramic views of the hills.",
    location: "Ooty",
    country: "India",
    price: 7000,
  },
  {
    title: "Riverside Camp",
    description: "Adventure camp beside the river with rafting and bonfire nights.",
    location: "Rishikesh",
    country: "India",
    price: 3500,
  },
  {
    title: "Island Resort",
    description: "Exclusive island resort with crystal-clear beaches and water sports.",
    location: "Andaman",
    country: "India",
    price: 12500,
  },
];

module.exports = { data : sampleListings };


const sampleListings1 = [
  {
    title: "Ocean View Apartment",
    description: "A spacious apartment with breathtaking views of the Arabian Sea.",
    location: "Kochi",
    country: "India",
    price: 7200,
  },
  {
    title: "Wooden Cottage",
    description: "A peaceful cottage surrounded by pine trees and fresh mountain air.",
    location: "Shimla",
    country: "India",
    price: 4100,
  },
  {
    title: "Royal Palace Stay",
    description: "Experience royal hospitality in a beautifully restored palace.",
    location: "Udaipur",
    country: "India",
    price: 9800,
  },
  {
    title: "Backwater Houseboat",
    description: "Enjoy a relaxing stay on a traditional houseboat with scenic backwater views.",
    location: "Alleppey",
    country: "India",
    price: 8500,
  },
  {
    title: "Luxury Farmhouse",
    description: "A modern farmhouse with a private garden and swimming pool.",
    location: "Pune",
    country: "India",
    price: 6800,
  },
  {
    title: "Skyline Studio",
    description: "Compact and stylish studio apartment in the city center.",
    location: "Hyderabad",
    country: "India",
    price: 3900,
  },
  {
    title: "Riverside Villa",
    description: "Beautiful villa located beside a peaceful river with scenic surroundings.",
    location: "Coorg",
    country: "India",
    price: 7600,
  },
  {
    title: "Hill View Resort",
    description: "A luxurious resort offering stunning sunrise and sunset views.",
    location: "Darjeeling",
    country: "India",
    price: 8900,
  },
  {
    title: "Eco Bamboo Hut",
    description: "Stay close to nature in an eco-friendly bamboo hut.",
    location: "Kaziranga",
    country: "India",
    price: 2600,
  },
  {
    title: "Business Hotel Suite",
    description: "Premium suite with workspace and modern amenities for business travelers.",
    location: "Delhi",
    country: "India",
    price: 9500,
  },
  {
    title: "Beachside Cottage",
    description: "Wake up to the sound of waves in this cozy beachside cottage.",
    location: "Gokarna",
    country: "India",
    price: 5400,
  },
  {
    title: "Historic Haveli",
    description: "Traditional haveli with handcrafted interiors and authentic local cuisine.",
    location: "Jodhpur",
    country: "India",
    price: 6100,
  },
  {
    title: "Camping Dome",
    description: "A unique dome tent experience under the stars with modern comforts.",
    location: "Spiti Valley",
    country: "India",
    price: 3300,
  },
  {
    title: "Lakefront Retreat",
    description: "Peaceful accommodation with direct access to a beautiful lake.",
    location: "Bhopal",
    country: "India",
    price: 4700,
  },
  {
    title: "Island Beach Resort",
    description: "Premium beachfront resort offering snorkeling, diving, and luxury stays.",
    location: "Lakshadweep",
    country: "India",
    price: 14000,
  },
];

module.exports = { dataa : sampleListings1 };